Users/2BitSalute/issue795_ignore_enum_member
json-everything/json-everything pull request #796
Opened 2024-09-25 01:09 UTC by 2BitSalute

### Description

The bug/feature is explained in [issue 795](https://github.com/json-everything/json-everything/issues/795).

This was a small change.

- In `EnumGeneration`, I just used the ignore/exclude conditions in `ObjectSchemaGeneration` 
- In `SchemaGenerationTests`, I added an enum with various attribute combinations, similar to the properties that were already tested, and added an expected schema property

For context, my scenario, which I think is not too uncommon:
- I'm generating a JSON schema for a config file
- I want to be able to use the schema to validate the config in a build step
- I also want users to be able to get IDE services for the JSON, so they can tell if they've specified invalid values
- We have an enum that, according to the [design guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/enum), specifies a member called `None`, which can be used to test the value to see if it were set or not.
- `None` should not be accepted as a valid value in the config in the build step
- `None` should also not be suggested in the IDE when users are authoring the config

### Links

Resolves https://github.com/json-everything/json-everything/issues/795

### Checks

- [X] I have read and understand the [Code of Conduct](https://github.com/json-everything/json-everything/blob/master/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/json-everything/json-everything/blob/master/CONTRIBUTING.md).

2024-09-25 01:11 UTC, 2BitSalute commented
@dotnet-policy-service agree company="Microsoft"

2024-09-25 22:33 UTC, gregsdennis requested changes
Overall looks great.  Thanks for putting it together.  Just some housekeeping comments.

I'll pull this into a new branch so I can manage version and release notes before publishing.

If you want, have a go at [updating the docs](https://github.com/json-everything/json-everything-docs/blob/aa1c7b60c620e31ba5c80bb83074cad4c2f86e95/_docs/schema/schemagen/schema-generation.md?plain=1#L122) as well (not required).

2024-09-25 22:33 UTC, gregsdennis commented on src/JsonSchema.Generation.Tests/SchemaGenerationTests.cs
> +		Ignore_ExcludesTrumpsIgnore,
```suggestion
		ExcludesTrumpsIgnore,
```

2024-09-25 22:33 UTC, gregsdennis commented on src/JsonSchema.Generation.Tests/SchemaGenerationTests.cs
> +		IgnoreThisBoth,
```suggestion
		IgnoreAndExclude,
```

2024-09-25 22:33 UTC, gregsdennis commented on src/JsonSchema.Generation/Generators/EnumGenerator.cs
> +		};
Please move to the top of the method (with a blank line underneath).

2024-09-25 22:33 UTC, gregsdennis commented on src/JsonSchema.Generation/Generators/EnumGenerator.cs
> +		var includedValues = values.Where(ShouldIncludeMember);
Please combine with the `.GetNames()` call and lose the `.ToList()`.

2024-09-27 23:09 UTC, 2BitSalute commented
Alright, I'll make the changes and add the docs!

2024-09-28 08:04 UTC, gregsdennis approved these changes

2024-09-29 04:15 UTC, 2BitSalute commented
Oops, sorry, closed by mistake - reopened

2024-09-29 06:04 UTC, merged